### PR TITLE
Update eclipse-keypop.jsonnet

### PR DESCRIPTION
**Pull request by pterr**
Add write access for GHActions

### CODE REVIEW

**Comment by netomi** [comment]
This is one of the settings where we would like to enforce "read" permissions. Each workflow should explicitly request write permissions if needed as explained here: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by netomi** [comment]
@pterr do you have a specific use-case in mind that would not work?

**Comment by netomi** [comment]
Hi @jeanpierrefortune 

ty for giving us context on this request.

In order to fix the failing workflow, you just need to add this to the update_dashboard.yml workflow file:

```
  deploy:
    permissions:
        contents: write
  ...
```

In general, you should consider deploying using an action rather than from a branch. This is a much cleaner solution. We use it ourselves for generating the self-service dashboard:

https://github.com/EclipseFdn/otterdog-configs/blob/main/.github/workflows/build_page.yml

This will just require some update to the configuration, let me know if you wanna make that change.

If you plan to utilize jenkins to build pages and deploy them to GitHub pages, the approach with the gh-pages branch is probably still the only option.

**Comment by netomi** [comment]
btw, the recent errors of the workflow:

```
Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_0d131659-edbd-4775-8deb-2f8447166e08/01298107-e77b-46f1-b442-fae1ecd908fa.tar.gz. return code: 2.
```

seem to be related to this bug: https://github.com/actions/checkout/issues/1448

some people reported that using v4 of the checkout action resolved it.

**Comment by netomi** [comment]
Can this PR then be closed after resolving the errors for the website?

**Comment by jeanpierrefortune** [comment]
Yes!
Thank you very must for the help!

**Pull request closed without merging**
