### PR TITLE
Activate GH Pages

### PR DESCRIPTION
**Pull request by pterr**

### CODE REVIEW

**Comment by netomi** [comment]
You need to add an environment similar to that when enabling GH Pages:

```
      environments: [
        newEnvironment('github-pages') {
          branch_policies: [
            "main"
          ],
          deployment_branch_policy: "selected",
        }
      ],
```

it could also just be something like that:

```
      environments: [
        newEnvironment('github-pages')
      ],
```


the reason is that GitHub will automatically create such an environment if otterdog does not do it.

**Comment by pterr** [comment]
OK, I can do the update to the environments.
About the 'branch_policies' list: should I set "gh-pages" instead of "main"?

For all pages, I want to generate the pages from / root directory of the gh-pages branch.

**Comment by netomi** [comment]
@pterr Indeed, that would be correct to use gh-pages as branch policy for the environment if you deploy from that branch. You could also just allow to publish from all branches, but that would be more clean imho.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
The change has been applied. However I had to do some changes I forgot about to tell you. When enabling the legacy build type and specify a branch to deploy from, this branch has to exist, as otherwise you will not be able to set that.

As a workaround, I specified the main branch for now and adjusted the configuration. Once you have created the gh-pages branch on all repos, we can change back to deploy from this branch.

In general, using workflow to deploy is the suggested method, you can take a look in one of our own repos, the workflow is really simple and very clean imho:

https://github.com/EclipseFdn/otterdog-configs/blob/main/.github/workflows/build_page.yml

**Comment by netomi** [comment]
Support for gh pages configuration has just been added recently, and there are still some rough edges we need to remove, sorry for the inconvenience.

The GH pages on the repos where it has been enabled, seems to have been deployed:

e.g. here https://github.com/eclipse-keypop/keypop-card-java-api/actions/runs/5752827583

**Pull request merged**
